deploy:
  api_key:
    - secure: ET6TIcDjoN/6EYzK5Ptkdxl5DQXpjFK0wbZomGNrM06Dq9sRmgVPNrCQXMknauYb0R0fYs7OG+F40Wd72WRPP9/IJieClqttgjtDBZUBPKRlz/QhRh8Q0KmK0JK/7qLZXMeAEH3QrMroT8CfVxF4c5b6eiCVO4dCfG6eKjzsJtD/XByn8QIegKCmV6m3NKMmQaJHdP7BIAQZVdga8LJTtKZ00iJGb8Yv5tUkgSK6i+rXxdMurYRM83wrBpMR68LzFoEqHkfSZi7SkJ/X887tBuRQNV9w/IQ6ruQh0xvjparlQEbxUk3q21NCQSK4u93RvCF+MbgTrkw80qVO2fofW0gHpf49m42TnwlLUpbsKBosZtDWryZPxVDOv9HSMn7S5h4RxdO9wmpi6f5/qF+k6Wr27xxTdyPOVOrxZpeU2JaMS4nP87kI7XAace1uj5PLPep1ppPtcgtEcO9m88tPKqJgjppjjth6QbBxZ0w0k9UNbYim94e5YQbnZrEaf79RYEE1Ji7slwwDjHBMXAvKfJr+aaUu+Ne+EVcVrFqcfIyYpQYwmoDLbKYWGKWb0nOCnCLX9EPD2hQG5LqJePwd9GL+yU9ibyEacCchQDOPcQYSnpOoY8DrTB8QEd8RASCKkmaYlHTt7CiQXvkCAZwGweIEmlmdBsZNiKaAXNIwfNw=
  app:
    master: johnny-cash-api
    develop: johnny-cash-staging-api
  provider: heroku
branches:
  only:
  - master
  - develop
language: node_js
node_js:
- 14
env:
  global:
  - secure: ET6TIcDjoN/6EYzK5Ptkdxl5DQXpjFK0wbZomGNrM06Dq9sRmgVPNrCQXMknauYb0R0fYs7OG+F40Wd72WRPP9/IJieClqttgjtDBZUBPKRlz/QhRh8Q0KmK0JK/7qLZXMeAEH3QrMroT8CfVxF4c5b6eiCVO4dCfG6eKjzsJtD/XByn8QIegKCmV6m3NKMmQaJHdP7BIAQZVdga8LJTtKZ00iJGb8Yv5tUkgSK6i+rXxdMurYRM83wrBpMR68LzFoEqHkfSZi7SkJ/X887tBuRQNV9w/IQ6ruQh0xvjparlQEbxUk3q21NCQSK4u93RvCF+MbgTrkw80qVO2fofW0gHpf49m42TnwlLUpbsKBosZtDWryZPxVDOv9HSMn7S5h4RxdO9wmpi6f5/qF+k6Wr27xxTdyPOVOrxZpeU2JaMS4nP87kI7XAace1uj5PLPep1ppPtcgtEcO9m88tPKqJgjppjjth6QbBxZ0w0k9UNbYim94e5YQbnZrEaf79RYEE1Ji7slwwDjHBMXAvKfJr+aaUu+Ne+EVcVrFqcfIyYpQYwmoDLbKYWGKWb0nOCnCLX9EPD2hQG5LqJePwd9GL+yU9ibyEacCchQDOPcQYSnpOoY8DrTB8QEd8RASCKkmaYlHTt7CiQXvkCAZwGweIEmlmdBsZNiKaAXNIwfNw=
